### PR TITLE
Gui/splash screen

### PR DESCRIPTION
**Pull request by BjornHo**
Executed #39. This splash screen shows up when our program is parsing and calculating segments. It also shows a loading progress bar and text above the bar which indicates what it is currently doing. I have also implemened multi threading because it is the only way to get this working. You cannot update the UI AND have heavy tasks running at the same time without freezing everything up. When it is done, the splash screen will perform a fade out transition and start up the usual "main" screen.
#37 is of course used as the splash screen which I designed as a logo for the program.

### CODE REVIEW

**Comment by DvdBerg** [comment]
Nice logo and splash screen! It would be my personal preference to have the splash screen slightly smaller and not resizable by the user. However, that is not really important and could probably be done easily in the future.

**Comment by HugoKooijman** [comment]
Looks good 👍  Now we have something to look at when data is loading and it looks more professional.

**Comment by RobKapel** [comment]
Looks impressive. It's nice to see the program is actually executing while processing the data, instead of nothing happening for several minutes. Good work!

**Comment by HatchIing** [comment]
Good to have a splash screen, nice job. You said that you resolved the conflicts in whatsapp so I think it's fine if we merge this in. Good stuff.

**Pull request merged**
