### PR TITLE
Gui/toolbar

### LINKED ISSUE #43: Read/write capability for recent files
Implement reading/writing the locations and names of recently opened files to/from a text file, so that the user can use the toolbar from #38 to open recent files as well.

### PR DESCRIPTION
**Pull request by BjornHo**
I fixed #43 and #38.
- Importing a new .gfa file, opening an existing database and opening a recent file works now. Recent also updates whenever another file is opened so the most recent will always be on top and there won't be duplicates there. The cap of most recent is set on 3.
- I have fixed all checkstyle warnings in my branch, including files which were actually not part of the implementation. Running maven site results in 0 warnings.
- I have made tests for the package toolbar. RecentHandler.java with coverage 85,1% and ExistingHandler 100%, resulting in an overall of 89,8%.
- I have fixed my tests so that it is fully compatible with travis. Travis gives build success.
- I have disabled the existing tests DatabaseReaderTest and GfaParserTest because they have conflicts with my tests since they do not clean up files afterwards. @HugoKooijman is fixing that.
- Do not touch .gitignore inside the recent folder.

### CODE REVIEW

**Comment by HugoKooijman** [comment]
Handy new options to work with. Will also help in further developing the project, since constant restarts and refreshes are now obsolete when just wanting to load another db.

I´ve fixed the test exceptions, will see later if ours do not collide.

PR approved.

**Comment by RobKapel** [comment]
Looks good, only found a little bug: if you try to import a gfa file of a database that already exists, it gives an error.

**Comment by BjornHo** [comment]
It should be fixed now. @RobKapel can you confirm that it works now?

**Comment by RobKapel** [comment]
Seems good now, I tested it and it doesn't give an error anymore.

**Pull request merged**
