### PR TITLE
Gui/enhancedzooming

### PR DESCRIPTION
**Pull request by RobKapel**
Implemented #77. When zooming, you will only zoom in the horizontal direction. Also fixed the issue when you zoom, that you couldn't keep track where you came from. The segments in the graph view are still scaled in a weird way, because they only change size now in horizontal direction. I tried resizing them based on this, but this made the program freeze, because computations took to long. Therefore, we keep the strange sizes for now, until we more dynamically can load in data.

### CODE REVIEW

**Comment by HatchIing** [comment]
Looks well done. Once we have collapsing bubbles the zoomed out view will look a lot better. Can you make sure that you don't push the database file?

**Comment by HugoKooijman** [comment]
Horizontal zoom alone will give a clearer overview of the graph, good work. I see you were in a harsh battle with testcases. It is a good tip for everyone that DbConnection should be closed, if your test involves a Dbm.

**Comment by DvdBerg** [comment]
Could you elaborate on "Also fixed the issue when you zoom, that you couldn't keep track where you came from"? Do you mean that you zoom in/out at the location of the cursor? I tried zooming, but it didn't seem to zoom in onto the cursor location. 

Also, I believe the customer requested that the graph fits on the screen (so there is no scroll bar) when completely zoomed out. Do you think you could add that?

Other than that, it looks good to me. The strange scaling of the nodes does not seem to be an issue, because we will integrate the two views in the future and only show the graph nodes when completely zoomed in.

**Comment by HatchIing** [comment]
With the previous zooming, when you zoomed with the scroll wheel, it zoomed and moved the scroll bar if I remember correctly. Now it looks like it locks the left side to stay at the same point when zooming.

**Comment by RobKapel** [comment]
Exactly what Evan said. Originally, when you tried zooming, the scroll bar didn't stay at the same place. Now, when you zoom in, you keep the same position on the scroll bar. You kan now keep track of a certain part of the ribbon/graph, without it suddenly disappearing from sight.

**Comment by DvdBerg** [comment]
Thanks for the explanation, I understand

**Comment by RobKapel** [comment]
Readjusted the maximum scale level, so you are able to see the entire graph/ribbon when completely zoomed out. I'll merge it right now.

**Pull request merged**
