### PR TITLE
Fix/graph phylo link

### PR DESCRIPTION
**Pull request by RobKapel**
#129 Fixed the problem of the graph not updating on selecting new genomes. Now it is working properly again, as in the previous release.

### CODE REVIEW

**Comment by DvdBerg** [comment]
Nice work! I've verified that it works correctly now and also checked that no PMD/Checkstyle/FindBugs warnings were introduced. One thing I noticed: you have changed the `changed` variable of `NewickNode` back to being a static variable. Is there a specific reason you did this? It seems to me that this variable is specific to a single instance of  `NewickNode` and is not shared between all instances.

**Comment by RobKapel** [comment]
You want to check whether a node has changed, you don't care that much which one. Therefore, instead of searching an entire tree, it's easier to use a static variable to mark that something changed in the tree. That's why I changed it back to being static.

**Comment by DvdBerg** [comment]
I see. Does it still work when it is not static or was that the cause of the malfunctioning? Because what if we would have multiple trees (multiple root nodes)? In that case, both trees would be marked as changed, when only one has actually changed. Currently we only display one tree, but it might be the case that we want to display multiple trees. However, if this was the cause of the malfunction, I can agree with it, since we will only display one tree in practice.

**Comment by HatchIing** [comment]
I also tested it and lt appears to be fine. I don't think it being static is that big of a problem right now though. I feel we can merge this.

**Comment by BjornHo** [comment]
I have tested it. Isn't it a bug that if I deselect everything, red lines are still being shown?

**Comment by DvdBerg** [comment]
It might be a bug, but it is not the bug that was being fixed here. I've added a corresponding issue to display what this pr fixes, as you can see in the initial comment that I updated.

**Pull request merged**
