### PR TITLE
Gui/tabs

### PR DESCRIPTION
**Pull request by BjornHo**
There is now a tab display. Each tab has one controller associated with it. I cleaned up the GUI code #13. RibbonDrawer has been removed since we now use the RibbonController for that. Screenmanager got removed because we don't need it (atleast for now) and it makes things a lot more complicated to manage (ironic isn't it?). 
I think with these changes everything gets nicely separated from each other in the GUI, before it was one big mess and nobody had any idea where to begin.

### CODE REVIEW

**Comment by HugoKooijman** [comment]
A needed adjustment to the gui. Good work, hopefully now we can get on with our work in normal fashion.

**Comment by RobKapel** [comment]
Looks good, now the GUI isn't that messy anymore.

Quick question though, why is this merged directly into master, and not the branch (Db/genomecount) it branched off off?

**Comment by BjornHo** [comment]
Because in my opinion it made no sense to have my changes inside a Db branch which had nothing to do with database. I needed your changes to test more efficiently. (1 sec vs 5 min image rendering time).

**Comment by RobKapel** [comment]
okay, that makes sense, then I can see why it can be merged immediately in the master. All clear now!

**Pull request merged**
