### PR TITLE
Db/fixnewdatasets

### LINKED ISSUE #64: Example set not loading

### PR DESCRIPTION
**Pull request by RobKapel**
Fix #64. The example dataset and the 328 genome data set are again working.

### CODE REVIEW

**Comment by DvdBerg** [comment]
I'm glad you managed to fix that bug, this will also help me when testing the ribbon collapsing. I am assuming you introduced the prints in the getGraphEdges() method to spot the cause of the bug. Could you remove them before merging? I believe a large amount of prints could possibly slow down the program.

**Comment by RobKapel** [comment]
Thanks for telling, they were indeed used to find the bug. Removed them immediately!

**Comment by BjornHo** [comment]
we **need** this change. Was very annoying that TB10 was the only working dataset..

**Comment by HugoKooijman** [comment]
Sorry about that, it would appear the bug was caused by me, for checking for the last Segment ID in the wrong arraylist.
PR approved!

**Pull request merged**
