### PR TITLE
Wrote tests for classes it made sense to.

### PR DESCRIPTION
**Pull request by HugoKooijman**
Tests for DatabaseManager and GfaParser now finished. Created additional test gfa files for test support.
Also, I commented out the Parser test, because currently if the parse() function is executed more than once, errors will start popping up. It requires auto-delete functionality, before more than 1 test can be run succesfully.

### CODE REVIEW

**Comment by BjornHo** [comment]
Nice to have some tests. I have a question about DatabaseReaderTest.
`private static DatabaseManager dbm;`
`private static GfaParser parser;`

Why static?

**Comment by HugoKooijman** [comment]
Because I used the @BeforeClass annotation above the before() test method. This means it will only execute the @before method once for the whole test class, instead of every time before each test.
Reason is because we have no automated database file removal yet. So if I execute the before() method (with the parse() method in it) more than once, it will give errors.

**Comment by HugoKooijman** [comment]
Because I used the @BeforeClass annotation above the before() test method. This means it will only execute the before() method once for the whole test class, instead of every time before each test.
Reason is because we have no automated database file removal yet. So if I execute the before() method (with the parse() method in it) more than once, it will give errors.

One requirement of the @BeforeClass annotation is that the variables used in the before() method are all made static (else eclipse will give compile errors).

**Comment by BjornHo** [comment]
Oh I see that makes sense. Ready to merge.

**Pull request merged**
