### PR TITLE
Gui/scrollpane

### LINKED ISSUE #42: Replace PannableCanvas
Improve the GUI code quality and readability by replacing the PannableCanvas with a ScrollPane, and (re-)adding zoom.

### PR DESCRIPTION
**Pull request by DvdBerg**
Fix  #42. Removed the PannableCanvas, SceneGestures, NodeGestures and DragContext classes, and added a ScrollPane to the Ribbon screen. Also fixed the Checktyle warnings in the modified files.

The controls now work in the following way:
- Dragging the mouse while the primary button is pressed will move the graph around.
- Using the scroll wheel will scroll the graph horizontally.
- Using the left/right tilt buttons of the scroll wheel will scroll the graph vertically.
- Using the scroll wheel while "Ctrl" is pressed will zoom in/out. I've chosen to only zoom in on the vertical axis, so that the orientation in the entire graph remains the same. Feel free to comment on this choice.

There was a possibility that #46 would also have been fixed by the use of a ScrollPane. This is not the case, however, as the graph is still invisible at startup and only appears after scrolling (after which it does not disappear anymore).

### CODE REVIEW

**Comment by BjornHo** [comment]
> Dragging the mouse while the primary button is pressed will move the graph around.
> Using the scroll wheel will scroll the graph horizontally.
> Using the left/right tilt buttons of the scroll wheel will scroll the graph vertically.

I tested it a bit and I noticed a few things.
1. Dragging the mouse moves the graph horizontally. Scroll wheel moves the graph horizontally. So I don't see what the difference is between moving the graph around and moving horizontally because for me they do the same thing.
2. The tilt button is not working at all for my mouse, nothing happens. I assume that you mean the "click" if you move the wheel to the left or to the right. I don't agree with this choice since not every mouse has that functionality, also somebody with a trackpad is unable to work with it.
3. The Ctrl zoom in/out does work but there is a problem. The more I zoom out, the more the graph walks up on my screen and I don't think that is as intended.

**Comment by DvdBerg** [comment]
Thanks for looking into the added functionalities. As for your remarks:
1. Dragging with the mouse can also move the graph vertically. I personally think being able to drag the graph with the mouse is expected behaviour, as is scrolling. The user can choose whichever one he likes most.
2. Indeed, with the tilt buttons I mean the left/right click of the scroll wheel. It is correct that not everyone will have this function available, but for those who do, it's a nice addition. I think certain trackpads also support horizontal scrolling (which is what the "tilt" button is to JavaFX). Trackpad users who cannot use this option can still use the scroll bar to the side of the screen, or drag the graph vertically.
3. I am aware of this problem. It is caused by the graph not being displayed in the (vertical) center of the screen. I tried to center it, but setting the y translation of the graph to half the size of the ScrollPane made the position too low, because the horizontal axis around which the graph is centered is not at y position 0, but lower. I will look into this problem when I have the time, but right now I need to spend my time to finish the phylogenetic tree visualization.

**Comment by RobKapel** [comment]
I'd prefer that while zooming, that the amounts of segments you see decreases. The current zooming is weird that it only zooms in one of the directions. Any comments on that?

**Comment by HugoKooijman** [comment]
I guess both zooming options could be handy, but when people zoom, they usually expect to zoom in on the entire image, not just stretching one axis. So zooming in over x and y seems to be more natural. Perhaps later with gigantic datasets would it be more helpful to zoom in over y only.

Overall nice work, we needed a better zooming and scrolling system.

**Comment by DvdBerg** [comment]
I can see why you think zooming should happen on both axes. I will add it shortly, along with support for zooming with the "+" and "-" keys while ctrl is held, and maybe travelling through the graph with the arrow keys as well.

**Comment by DvdBerg** [comment]
I've changed the zooming so that it zooms on both axes now. I've also added an event handler to zoom with the  "+" and "-" keys while ctrl is held. The arrow keys are currently used to switch the tabs of the TabPane, but we can easily change that in the future if we want to. For now, I will merge this PR once all checks have passed.

**Pull request merged**
