### PR TITLE
Tooling fixes

### PR DESCRIPTION
**Pull request by DvdBerg**
Hugely reduced the number of warnings from the static code analysis tools.

### CODE REVIEW

**Comment by RobKapel** [comment]
There still seem to be some bugs left. (FindBugs) Why are those not removed?

**Comment by HatchIing** [comment]
Good job removing the vast majority. Why are there still those 16 bugs left?

**Comment by DvdBerg** [comment]
We disagreed with some of the supposed errors that FindBugs located, thus we have not removed every single one of them. For example, FindBugs was complaining about a getter that returns a private variable from the class.

**Comment by RobKapel** [comment]
Okay, then I understand why those are not removed. Good for the rest!

**Comment by HatchIing** [comment]
Alright, that sounds fine. Thanks for critically thinking about the bugs to fix.

**Pull request merged**
