### PR TITLE
Fix/phylocolours

### PR DESCRIPTION
**Pull request by HugoKooijman**
Parent nodes in the Phylogenetic tree now know the lineage of their children. Higher parent nodes with 2 children of different lineages remain coloured black, because there's not 1 colour that applies to these nodes.

Also cleaned up messy code, divided it more into smaller methods.

As for the edges, using the Path class makes it either really difficult or impossible to colour them. This is because HLineTo and VLineTo objects cannot be coloured.
Also, the pruneTree methods don't help in fixing the problem of overlapping nodes/edges, because they're basically a dirty fix to remove nodes after calculating the complete tree. The problem is, that the edges are still drawn, and to their individual moveTo's, not to the next node. So if you translate the startposition of a VLineTo or an HLineTo, it will stretch out VLineTo's and HLineTo's of nodes that were removed, resulting in many weird small lines.
Trying to colour a pruned Tree will result in all kinds of weird half-coloured triangles, presumably caused by the HLineTo and VLineTo covering a certain area that is not readily apparent.

I plan to replace the VLineTo and HLineTo objects with Line objects, which are vastly more customizable. The Path class just seems like a poor choice for a tree.

### CODE REVIEW

**Comment by BjornHo** [comment]
I think it is better to wait till the edge problem is solved before merging into master.

**Comment by DvdBerg** [comment]
I don't understand that you want to merge unfinished code that still has lots of problems into the master branch. There is no reason to do that.

**Comment by HugoKooijman** [comment]
Well there's less problems with this code than with the code in the master. I thought we could merge this to make this the current standard, then other people can branch off of it to improve upon it. I was going to make a new branch after this to refactor the newickedges.

**Comment by DvdBerg** [comment]
That you fixed some problems is good, but from your description it seems there are still a lot of problems left. I still don't see why we would put this in master currently, as it does not fix an issue and only fixes some of the problems with the code in master. Also, the code doesn't need to be in master before you can use it in another branch: you can still branch from master to refactor the newickedges and then merge `fix/phylocolours` into that branch.

**Pull request merged**
